apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storage.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.storage.service.type }}
  ports:
  {{- range .Values.storage.service.ports }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
    name: {{ .name }}
  {{- end }}
  selector:
    app: {{ .Values.storage.name }}