apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yatai-cluster-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  ingressClassName: nginx
  tls: 
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
      - {{ . }}.{{ $.Values.ingress.domain }}
    {{- end }}
    secretName: {{ .secretName }}-yatai-cluster-tls
  {{- end }}
  rules:
  {{- range .Values.ingress.rules }}
  - host: {{ .host }}.{{ $.Values.ingress.domain }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
      {{ end }}
  {{- end }}